name: Schedule Worker

# on: workflow_dispatch
on:
  schedule:
    - cron: "33 */1 * * *"
  workflow_dispatch:
  

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: szenius/set-timezone@v1.0 # 设置执行环境的时区
        with:
          timezoneLinux: "Asia/Shanghai"
      - uses: actions/setup-python@v1 # 使用python装配器
        with:
          python-version: 3.8
          cache: 'pip'
      - run: pip install -r requirements.txt
      
      - name: Run
        run: |
          python -v
          python GenMM.py

#       - name: commit
#         run: |
#           git config user.name "1842074134"
#           git config user.email "1842074134@qq.com"
#           git add mmzxsp
#           git commit -m "updata" mmzxsp
#           git pull "https://github.com/mlabalabala/test.git" main

#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          author_name: "GitHub Action"
          author_email: "action@github.com"
          message: "Updata"
          add: "*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Mirror the Github repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/mlabalabala
          dst: gitee/mlabalabala
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "mm"
          force_update: true



# on: workflow_dispatch
 
# jobs:
#   run:
#     runs-on: ubuntu-latest
 
#     steps:
#     - name: Hello World
#       run: |
#         echo My name is P3TERX.
#         echo Hello World!
